### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [marioaquino/LOLcode.tmbundle#1]
I would like to use your grammar for LOLCODE but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by marioaquino** [comment]
No sweat. Thanks for reaching out. I'll add a license shortly.

**Comment by marioaquino** [comment]
Done.  Thanks for asking.

**Comment by pchaigno** [comment]
Thanks!

**Comment by pchaigno** [comment]
@marioaquino Your grammar is now used to highlight LOLCODE code on GitHub (files and code snippets in Markdown documents)! (See github/linguist#2071 for more information.)
